### ISSUE TITLE
neoscrypt segfaults

### ISSUE THREAD

**Issue by crackfoo** [tpruvot/yiimp#4]
I've found that whenever a miner connects to neo stratum is segfaults. built with debug and backtraced:

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff48e1700 (LWP 29892)]
0x000000000043044d in neoscrypt_fastkdf.constprop ()
(gdb) bt
#0  0x000000000043044d in neoscrypt_fastkdf.constprop ()
#1  0x00000000004313fb in neoscrypt ()
#2  0x0000000000403a85 in neoscrypt_hash (input=0x7ffff48dfe50 "\002", output=0x7ffff48e0a50 "", len=80) at stratum.cpp:80
#3  0x0000000000413512 in build_submit_values (submitvalues=0x7ffff48de250, templ=0x7836a0, nonce1=0x7fffe8001d30 "81000001", nonce2=0x7ffff48e0e50 "09000000", ntime=0x7ffff48e0e70 "565f966c", nonce=0x7ffff48e0e90 "0002821d")
    at client_submit.cpp:41
#4  0x00000000004146eb in client_submit (client=0x7fffe80008c0, json_params=0x7fffe8002c80) at client_submit.cpp:282
#5  0x0000000000412f30 in client_thread (p=0xa) at client.cpp:426
#6  0x00007ffff7bc26aa in start_thread (arg=0x7ffff48e1700) at pthread_create.c:333
#7  0x00007ffff6816eed in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
(gdb)

Any ideas why?

**Comment by crackfoo** [comment]
This issue was happening on Ubuntu 15.10 Wily. I was able to modify the make files which resolved the issue. These commands will adjust the makefiles with the appropriate values

# sed -i 's/-O3/-O2/' algos/makefile
# sed -i 's/-O3/-O2/' Makefile

**Comment by crackfoo** [comment]
fixed in this commit:

https://github.com/tpruvot/yiimp/commit/b197a17a49b26b198e212702db2cc06116f67127
