### ISSUE TITLE
Bleutrade & Poloniex scripts crash after withdraw performed

### ISSUE THREAD

**Issue by crackfoo** [tpruvot/yiimp#5]
I know you're not focusing on the exchanging bits, but thought I'd log this just the same in case someone else has a solution or you have time. Seems both scripts  error out when running the scripts from the dashboard and your EXCH_AUTO_WITHDRAW limit is reached. The withdraws are actually performed, but the script doesn't finish properly.

2015/12/03 17:28:29 [error] [php] Trying to get property of non-object (/web/yaamp/core/trading/bleutrade_trading.php:212)
Stack trace:
#0 /pool/web/framework-1.0.8/web/CController.php(300): CInlineAction->run()
#1 /pool/web/framework-1.0.8/web/CController.php(278): SiteController->runAction()
#2 /pool/web/framework-1.0.8/web/CController.php(257): SiteController->runActionWithFilters()
#3 /pool/web/framework-1.0.8/web/CWebApplication.php(335): SiteController->run()
#4 /pool/web/framework-1.0.8/web/CWebApplication.php(123): CWebApplication->runController()
#5 /pool/web/framework-1.0.8/base/CApplication.php(134): CWebApplication->processRequest()
#6 /pool/web/index.php(20): CWebApplication->run()
REQUEST_URI=/site/runExchange?id=4

2015/12/03 17:59:57 [error] [php] Trying to get property of non-object (/home/crackers/zpool/web/yaamp/core/trading/poloniex_trading.php:172)
Stack trace:
#0 /pool/web/framework-1.0.8/web/CController.php(300): CInlineAction->run()
#1 /pool/web/framework-1.0.8/web/CController.php(278): SiteController->runAction()
#2 /pool/web/framework-1.0.8/web/CController.php(257): SiteController->runActionWithFilters()
#3 /pool/web/framework-1.0.8/web/CWebApplication.php(335): SiteController->run()
#4 /pool/web/framework-1.0.8/web/CWebApplication.php(123): CWebApplication->runController()
#5 /pool/web/framework-1.0.8/base/CApplication.php(134): CWebApplication->processRequest()
#6 /pool/web/index.php(20): CWebApplication->run()
REQUEST_URI=/site/runExchange?id=2

**Comment by crackfoo** [comment]
Fixed in this commit:

https://github.com/tpruvot/yiimp/commit/bc8f444f94f730aa7f2a4e0889b186c5f0bf4cf0
